### ISSUE TITLE
How to compute the madd of layers with two inputs (such as Bilinear)

### ISSUE THREAD

**Issue by gasvn** [ceykmc/pytorch_model_summary#2]
Your tool is so useful!
However, I found that your tool doesn't support the madd of layers with two inputs (such as Bilinear). I tried to add a compute_Bilinear_madd func, but I am confused about the input. It seems you use input[0] as the input of a layer (madd = compute_module_madd(module, input[0], output)). How can I achieve this function with min effort？

**Comment by gasvn** [comment]
And I have finished a primary version where supposed that input1 = input2
```
def compute_Bilinear_madd(module, inp, out):
    # suppose that input1 = input2
    assert isinstance(module, nn.Bilinear)
    assert len(inp.size()) == 2 and len(out.size()) == 2

    num_in_features = inp.size()[1]
    num_out_features = out.size()[1]

    mul = num_in_features*num_in_features
    add = num_in_features - 1
    return num_out_features * (mul + add)
```
Hop there is no mathematical error ^-^

**Comment by yogurt7771** [comment]
Can you tell me why it's calculated as this?

**Comment by gasvn** [comment]
@patrickwangqy sorry to confuse you, I just made a simple guess the other day. And I have corrected it.
Here is the new code.
```
def compute_Bilinear_madd(module, inp, out):  # inp is no longer input[0] but input
    assert isinstance(module, nn.Bilinear)
    assert len(inp[0].size()) == 2 and len(out.size()) == 2
    
    num_in_features_1 = inp[0].size()[1]
    num_in_features_2 = inp[1].size()[1]
    num_out_features = out.size()[1]

    mul = num_in_features_1*num_in_features_2 + num_in_features_2
    add = num_in_features_1*num_in_features_2 + num_in_features_2 - 1
    return num_out_features * (mul + add)
```
I write a simple note to explain why it's calculated as this.

https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetmsgimg?&MsgID=8522162385482526989&skey=%40crypt_480e0fb5_c992ac29c293f3ca0a3b1c58f68ade96

What I don't understand is why you '- 1' when calculate add.
