### ISSUE TITLE
What does MAdd mean exactly?

### ISSUE THREAD

**Issue by msson** [ceykmc/pytorch_model_summary#4]
1 Madd is 2 Flops? and 1 Madd is 1 MAc?

Is this right?

Thanks.

**Comment by ceykmc** [comment]
According to MobileNet, MAdd means multiply-adds, number of operations.
Here, we just accumulate multiply operation  and add operation.
1 Madd is 1 Flops, either float multiply or  float add.

**Comment by msson** [comment]
Thanks for your reply! I also have two questions.

1. How can I apply PReLU instead of ReLu in this summary tool? I can see this error below when I run the code with my model. (I can get MAdd with PReLu but I don't know the result is right because of the error.)  
![questions](https://user-images.githubusercontent.com/35793913/47481838-d0bfcb80-d86f-11e8-802e-663a0f28302a.png)

2. As you see above image, the summary list does not contain all values, but I can check the variable 'df' has all values so I guess this is print() command problem. Could you let me know how to print all the list?

**Comment by ceykmc** [comment]
1. PReLU
    module_madd.py line:153
    elif isinstance(module, (nn.ReLU, nn.ReLU6)):  --> elif isinstance(module, (nn.ReLU, nn.ReLU6, nn.PReLU)):
    module_madd.py line:96
    assert isinstance(module, (nn.ReLU, nn.ReLU6))  --> assert isinstance(module, (nn.ReLU, nn.ReLU6, nn.PReLU))
2. model_summary.py line:12
   add a new line:
   pd.set_option('display.max_columns', 10000)

**Comment by msson** [comment]
Thanks a lot!
