### ISSUE TITLE
Definition of Inference Memory

### ISSUE THREAD

**Issue by euler16** [ceykmc/pytorch_model_summary#6]
Hi,
Thanks for this repository.
I wanted to understand what you mean by inference memory : is it the memory size of the model, or does it refer to amount of memory the model consumes (RAM) during inference.

**Comment by ceykmc** [comment]
It's the temporary memory of the output in each layer.
It was computed by multiply the output shape, and output dtype was assumed to be float32.

**Comment by euler16** [comment]
so can I say (inference memory / (size of dtype)) + parameter size = number of memory access?

memory access as defined [here](https://machinethink.net/blog/how-fast-is-my-model/)

**Comment by ceykmc** [comment]
The parameters are excluded.
model_hook.py, line 65
you can add them

**Comment by euler16** [comment]
okay thanks :)
