### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by h-jia** [ceykmc/pytorch_model_summary#7]
Closed

**Comment by ceykmc** [comment]
didn't consider RNN module when i write it.
add RNN module is an interesting feature, i will add it during my new year holiday.

**Comment by h-jia** [comment]
Thanks! Looking forward to seeing it. Happy Chinese New Year!

**Comment by h-jia** [comment]
Hi, is this repo still maintaining? Thanks.

**Comment by ceykmc** [comment]
sorry for not reply, but you may consider this better repository:
https://github.com/NervanaSystems/distiller

**Comment by h-jia** [comment]
Hi Thanks. It looks very informative. Appreciate!

**Comment by mjrudnik** [comment]
I don't see how distiller can do the same analysis with mAdds like you repository does.
Do you have an example for how to use distiller for analysis?
